export const DETAILED_MUSCLE_SOURCE = {
  repository:'Nurkan1/Anatria-3D',
  commit:'949ac80cc9763539afc48e60b5246132f00468db',
  runtimeAsset:'/models/z-muscular-male.glb',
  runtimeManifest:'/models/z-muscles-manifest.json',
  license:'CC BY-SA 4.0',
  expectedMeshCount:484,
  scope:'Actual muscle meshes selected from the pinned Z-Anatomy hierarchy. Muscular insertion markings and non-muscle support structures are excluded.'
} as const;

export const ARTICULAR_SOURCE = {
  repository:'Nurkan1/Anatria-3D',
  commit:'949ac80cc9763539afc48e60b5246132f00468db',
  runtimeAsset:'/models/z-articular-male.glb',
  runtimeManifest:'/models/z-articular-manifest.json',
  license:'CC BY-SA 4.0',
  expectedMeshCount:413,
  scope:'Pinned articular-system meshes including joint capsules, discs, menisci and ligaments where present in the source hierarchy.'
} as const;

export const HEAD_MUSCLE_SOURCE = {
  repository:'Nurkan1/Anatria-3D',
  commit:'949ac80cc9763539afc48e60b5246132f00468db',
  asset:'public/anatomy/muscular_male.glb',
  runtimeAsset:'/models/z-muscular-male.glb',
  derivedFrom:['Z-Anatomy','BodyParts3D'],
  license:'CC BY-SA 4.0',
  expectedMeshCount:78,
  anatomicalPairs:39,
  scope:'All actual muscle meshes present in the pinned source hierarchy for Cranial part / Muscles of head plus Suboccipital muscles. Non-muscle support meshes are excluded.'
} as const;

export const HEAD_MUSCLE_SOURCE_NODES = [
  "Bucinator.l",
  "Bucinator.r",
  "Corrugator supercilii.l",
  "Corrugator supercilii.r",
  "Deep part of masseter.l",
  "Deep part of masseter.r",
  "Depressor anguli oris.l",
  "Depressor anguli oris.r",
  "Depressor labii inferioris.l",
  "Depressor labii inferioris.r",
  "Depressor septi nasi.l",
  "Depressor septi nasi.r",
  "Frontalis muscle.l",
  "Frontalis muscle.r",
  "Genioglossus muscle.l",
  "Genioglossus muscle.r",
  "Hyoglossus muscle.l",
  "Hyoglossus muscle.r",
  "Inferior head of lateral pterygoid muscle.l",
  "Inferior head of lateral pterygoid muscle.r",
  "Inferior oblique muscle.l",
  "Inferior oblique muscle.r",
  "Inferior rectus muscle.l",
  "Inferior rectus muscle.r",
  "Lateral rectus muscle.l",
  "Lateral rectus muscle.r",
  "Levator anguli oris.l",
  "Levator anguli oris.r",
  "Levator labii superioris.l",
  "Levator labii superioris.r",
  "Levator nasolabialis.l",
  "Levator nasolabialis.r",
  "Levator palpebrae superioris.l",
  "Levator palpebrae superioris.r",
  "Medial pterygoid muscle.l",
  "Medial pterygoid muscle.r",
  "Medial rectus muscle.l",
  "Medial rectus muscle.r",
  "Mentalis muscle.l",
  "Mentalis muscle.r",
  "Nasalis muscle.l",
  "Nasalis muscle.r",
  "Obliquus inferior capitis muscle.l",
  "Obliquus inferior capitis muscle.r",
  "Obliquus superior capitis muscle.l",
  "Obliquus superior capitis muscle.r",
  "Occipitalis muscle.l",
  "Occipitalis muscle.r",
  "Orbicularis oris muscle.l",
  "Orbicularis oris muscle.r",
  "Orbital part of orbicularis oculi.l",
  "Orbital part of orbicularis oculi.r",
  "Palpebral part of orbicularis oculi.l",
  "Palpebral part of orbicularis oculi.r",
  "Procerus muscle.l",
  "Procerus muscle.r",
  "Rectus posterior major capitis muscle.l",
  "Rectus posterior major capitis muscle.r",
  "Rectus posterior minor capitis muscle.l",
  "Rectus posterior minor capitis muscle.r",
  "Risorius muscle.l",
  "Risorius muscle.r",
  "Superficial part of masseter.l",
  "Superficial part of masseter.r",
  "Superior head of lateral pterygoid muscle.l",
  "Superior head of lateral pterygoid muscle.r",
  "Superior oblique muscle.l",
  "Superior oblique muscle.r",
  "Superior rectus muscle.l",
  "Superior rectus muscle.r",
  "Temporalis muscle.l",
  "Temporalis muscle.r",
  "Temporoparietalis muscle.l",
  "Temporoparietalis muscle.r",
  "Zygomaticus major muscle.l",
  "Zygomaticus major muscle.r",
  "Zygomaticus minor muscle.l",
  "Zygomaticus minor muscle.r"
] as const;
