import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import YhctStudyPanel,{type StudyCommand} from './yhct-study-panel';
import RegistrationPanel from './registration-panel';
import Meridian3DPanel from './meridian-3d-panel';
import {type MeridianFocusTarget,type MeridianOverlayState} from './meridian-overlay';
import {type RenderQualityMode} from './render-quality';
import {type AcupointAnchorDraft,type RegistrationSide,type SurfaceCapture} from '../src/acupoints/registration/coordinate-system';
import {normalizeAtlasSystems,DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,anatomyName,explanation,isMeridianLandmarkMuscle,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
import {ARTICULAR_SOURCE,DETAILED_MUSCLE_SOURCE,SKELETAL_SOURCE} from './head-muscles';
const initial:SceneState={headMuscles:false,explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
const REGISTRATION_STORAGE_KEY='hiu-yhct-registration-drafts-v0.1';
const RENDER_QUALITY_STORAGE_KEY='hiu-atlas-render-quality-v1';
const BUILD_SHA=(import.meta.env.VITE_BUILD_SHA||'dev').slice(0,12);
const readRenderQuality=():RenderQualityMode=>{if(typeof window==='undefined')return 'auto';try{const value=localStorage.getItem(RENDER_QUALITY_STORAGE_KEY);return value==='economy'||value==='high'||value==='auto'?value:'auto'}catch{return 'auto'}};
const emptyMeridianOverlay:MeridianOverlayState={enabled:false,meridianId:null,side:'BOTH',anchors:[],paths:[]};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const [registrationEnabled,setRegistrationEnabled]=useState(false),[registrationTarget,setRegistrationTarget]=useState<{pointCode:string;side:RegistrationSide}>({pointCode:'ST-36',side:'LEFT'}),[registrationCapture,setRegistrationCapture]=useState<SurfaceCapture|null>(null);
 const [registrationDrafts,setRegistrationDrafts]=useState<AcupointAnchorDraft[]>([]),[meridianOverlay,setMeridianOverlay]=useState<MeridianOverlayState>(emptyMeridianOverlay),[meridianFocus,setMeridianFocus]=useState<MeridianFocusTarget|null>(null),[selectedMeridianPoint,setSelectedMeridianPoint]=useState<string|null>(null);
 const [renderQuality,setRenderQuality]=useState<RenderQualityMode>(readRenderQuality);
 const studyCommandSeq=useRef(0),[studyCommand,setStudyCommand]=useState<(StudyCommand&{seq:number})|null>(null);
 useEffect(()=>{const abort=new AbortController();const timeout=setTimeout(()=>{setError('Tải danh mục quá thời gian. Kiểm tra kết nối và tải lại.');abort.abort();},20000);setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch(import.meta.env.BASE_URL+'models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Không tải được danh mục giải phẫu.');return r.json();}).then(data=>{clearTimeout(timeout);setAtlas(normalizeAtlasSystems(data as Atlas));}).catch(e=>{clearTimeout(timeout);if(e.name!=='AbortError')setError(e.message);});return()=>{clearTimeout(timeout);abort.abort();};},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{const enabled=new URLSearchParams(window.location.search).get('register')==='1';setRegistrationEnabled(enabled);if(enabled)setState(s=>({...s,explode:0,isolate:false,rotate:false,visible:s.visible.includes('integumentary')?s.visible:[...s.visible,'integumentary']}));},[]);
 useEffect(()=>{try{const saved=localStorage.getItem(REGISTRATION_STORAGE_KEY);if(saved)setRegistrationDrafts(JSON.parse(saved));}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(RENDER_QUALITY_STORAGE_KEY,renderQuality)}catch{}},[renderQuality]);
 useEffect(()=>{
  if(!registrationEnabled)return;
  setState(s=>{
   const hasSkin=s.visible.includes('integumentary');
   if(s.explode===0&&!s.isolate&&!s.rotate&&hasSkin)return s;
   return {...s,explode:0,isolate:false,rotate:false,visible:hasSkin?s.visible:[...s.visible,'integumentary']};
  });
 },[registrationEnabled,state.explode,state.isolate,state.rotate,state.visible]);
 useEffect(()=>{
  if(!meridianOverlay.enabled)return;
  setState(s=>{
   const hasSkin=s.visible.includes('integumentary');
   if(s.explode===0&&!s.isolate&&!s.rotate&&hasSkin)return s;
   return {...s,explode:0,isolate:false,rotate:false,visible:hasSkin?s.visible:[...s.visible,'integumentary']};
  });
 },[meridianOverlay.enabled,state.explode,state.isolate,state.rotate,state.visible]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>{const base=atlas?.parts.filter(p=>p.system===s.id).length??0;if(s.id==='skeletal')return[s.id,SKELETAL_SOURCE.expectedMeshCount];if(s.id==='articular')return[s.id,ARTICULAR_SOURCE.expectedMeshCount];if(s.id==='muscular')return[s.id,atlas?.parts.filter(p=>p.system==='muscular'&&isMeridianLandmarkMuscle(p.name)).length??0];return[s.id,base]})),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleBaseCount=atlas?.parts.filter(p=>{const selected=state.selected.includes(p.id);if(state.isolate)return selected;if(p.system==='muscular'&&!selected&&!isMeridianLandmarkMuscle(p.name))return false;return state.visible.includes(p.system)||selected;}).length??0;
 const focusedReplacementCount=!state.isolate&&state.explode<.01&&state.visible.length===1?(state.visible[0]==='skeletal'?SKELETAL_SOURCE.expectedMeshCount:state.visible[0]==='articular'?ARTICULAR_SOURCE.expectedMeshCount:null):null;
 const visibleCount=focusedReplacementCount??visibleBaseCount;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>anatomyName(c.name).toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const handleStudyCommand=(command:StudyCommand)=>{
  if(command.view)setState(s=>({...s,view:command.view!,reset:s.reset+1,rotate:false}));
  const {view:_,...overlayCommand}=command;
  if(overlayCommand.meridianId||overlayCommand.pointCode||overlayCommand.effects)setStudyCommand({...overlayCommand,seq:++studyCommandSeq.current});
 };
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} renderQuality={renderQuality} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError} registrationMode={registrationEnabled} onRegisterSurface={setRegistrationCapture} meridianOverlay={meridianOverlay} focusAcupoint={meridianFocus} onSelectAcupoint={setSelectedMeridianPoint}/>} 
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> HIU CLB YHCT · ATLAS GIÁO DỤC</div><h1>HIU YHCT Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} cấu trúc giải phẫu <span>·</span> BodyParts3D</div></header>
  <YhctStudyPanel localDraftCount={registrationDrafts.length} onStudyCommand={handleStudyCommand}/>
  <Meridian3DPanel drafts={registrationDrafts} selectedPointCode={selectedMeridianPoint} studyCommand={studyCommand} onOverlayChange={setMeridianOverlay} onFocus={setMeridianFocus}/>
  {registrationEnabled&&<RegistrationPanel target={registrationTarget} capture={registrationCapture} onTargetChange={next=>{setRegistrationTarget(next);setRegistrationCapture(null);}} onDraftsChange={setRegistrationDrafts}/>} 
  <nav className="top-actions" aria-label="Bảng điều khiển"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Tìm giải phẫu"><Search size={18}/><span>Tìm cấu trúc</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="Thông tin ứng dụng" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Lớp giải phẫu">
   <div className="panel-heading"><span>Hệ cơ quan</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Đóng hệ cơ quan"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='integumentary'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['integumentary']}))}>Bề mặt</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Bộ xương</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='muscular'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['muscular']}))}>Cơ mốc</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='articular'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['articular']}))}>Khớp</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Nội tạng</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Chỉ hiện ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Hiện ${s.name.toLowerCase()}`} /></div>)}</div>
   <label className="quality-control" data-render-quality-control="true"><span>Chất lượng hiển thị</span><select value={renderQuality} onChange={e=>setRenderQuality(e.target.value as RenderQualityMode)} aria-label="Chất lượng hiển thị 3D"><option value="auto">Tự động</option><option value="economy">Tiết kiệm</option><option value="high">Chất lượng cao</option></select><small>Tự động dùng khả năng WebGL và nhịp khung hình thực tế; dữ liệu thiết bị chỉ xử lý trên máy.</small></label>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} cấu trúc đang hiện</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Ẩn tất cả</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Tìm giải phẫu"><div className="panel-heading"><span>Tìm cấu trúc</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Đóng tìm kiếm"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>anatomyName(c.name)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Tim, xương đùi, thần kinh sọ…" aria-label="Tìm theo tên cấu trúc giải phẫu" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>Không tìm thấy cấu trúc phù hợp.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{anatomyName(c.name)}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'cấu trúc':'cấu trúc'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Hiển thị tối đa 80 kết quả. Nhập tên cụ thể để thu hẹp tìm kiếm.':'Chọn cơ quan hoặc tìm cấu trúc theo tên Việt/Anh.'}</p></section>}
  <nav className="view-controls glass" aria-label="Điều khiển góc nhìn">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} onClick={()=>setState(s=>({...s,view:v,explode:s.explode>.8?.78:s.explode,reset:s.reset+1,rotate:false}))} title={['Góc nghiêng','Mặt trước','Mặt bên','Mặt sau'][i]} aria-label={['Góc nghiêng','Mặt trước','Mặt bên','Mặt sau'][i]}><span>{['¾','Trước','Bên','Sau'][i]}</span></Button>)}<i/><Button variant="ghost" data-auto-rotate-toggle="true" aria-label={state.rotate?'Dừng xoay':'Xoay mô hình'} title="Tự động xoay" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,explode:s.explode>=.4?.35:s.explode,rotate:!s.rotate,reset:s.reset+(s.explode>=.4?1:0)}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" data-reset-view="true" aria-label="Đặt lại góc nhìn và lớp" title="Đặt lại" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'CẤU TRÚC ĐÃ CHỌN'):state.explode>.95?'CÁC CẤU TRÚC GIẢI PHẪU':state.explode>.05?'CẤU TRÚC TÁCH RỜI':'NGƯỜI TRƯỞNG THÀNH · NAM'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Mở lớp cơ quan"><Layers3 size={20}/><span>Hệ cơ quan</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Tách lớp giải phẫu</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Ghép liền</span><span>Tách từng phần</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Ghép và đặt lại"><RotateCcw size={18}/><span>Đặt lại</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Kéo để di chuyển':'Kéo để xoay'} <b>·</b> Chụm để thu phóng <b>·</b> Chạm để xem <small data-build-sha={BUILD_SHA}>· build {BUILD_SHA}</small></span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Nguồn và thông tin <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Đang tải giải phẫu</strong><span>{progress}% · Đang tải {atlas?.parts.length.toLocaleString()??'2,234'} cấu trúc</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Tải lại mô hình</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'GIẢI PHẪU'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?anatomyName(chosen.name):''}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">Tổng quan hệ cơ quan · cấu trúc theo dữ liệu nguồn</span>}<div className="structure-meta"><span>Mã tham chiếu<strong>{chosen?.id}</strong></span><span>Số phần đã chọn<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Cấu trúc thành phần</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{anatomyName(p.name)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>Còn {selectedParts.length-50} phần mô hình khác.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">Xem nguồn giải phẫu <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Hiện cấu trúc xung quanh':'Xem riêng cấu trúc'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Bỏ chọn</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">THÔNG TIN VÀ PHẠM VI</div><SheetTitle className="structure-title">Thông tin ứng dụng</SheetTitle><SheetDescription>Huyệt vị · Kinh lạc · Giải phẫu 3D — HIU CLB YHCT.</SheetDescription><div className="about-copy"><p><strong>Mô hình nam · BodyParts3D</strong><br/>2.234 khối hình và 3.432 khái niệm giải phẫu từ mô hình nam trưởng thành.</p><p><strong>Mô hình ưu tiên kinh–huyệt</strong><br/>Lớp cơ mặc định chỉ hiển thị nhóm cơ mốc bề mặt chọn lọc từ BodyParts3D; toàn bộ kho 484 mesh cơ Z-Anatomy được giữ ở mức tham chiếu và không tải vào runtime. Lớp xương ({SKELETAL_SOURCE.expectedMeshCount} mesh) và khớp ({ARTICULAR_SOURCE.expectedMeshCount} mesh) chỉ tải khi người học chủ động bật.</p><p>Mô hình không bao gồm mọi cấu trúc và biến thể cơ thể. Một khái niệm có thể gồm nhiều phần hình học.</p><p>Màu sắc và nhóm cơ quan hỗ trợ tra cứu học tập. Hình học được giản lược để hiển thị trên web. Ứng dụng không dùng để chẩn đoán hay hướng dẫn thủ thuật.</p><h3>Tọa độ và hiệu ứng mô phỏng</h3><p data-simulation-notice="true">Vị trí huyệt và đường kinh trên mô hình 3D là tọa độ mô phỏng phục vụ học tập, chưa được thẩm định vị trí giải phẫu. Dòng sáng chuyển động chỉ là hiệu ứng minh họa, không biểu thị dòng chảy sinh lý được đo. Không dùng để xác định vị trí châm cứu trên người.</p><p>Tiếng Việt là ngôn ngữ chính; tiếng Anh và tiếng Trung dùng để tham khảo bổ sung. Tên cấu trúc nguồn chưa có bản dịch được giữ nguyên.</p><h3>Tối ưu thiết bị</h3><p>Chế độ Tự động dùng WebGL, kích thước màn hình, mật độ điểm ảnh và các gợi ý CPU/RAM mà trình duyệt cho phép, sau đó điều chỉnh theo nhịp khung hình đo được. Thông tin này chỉ dùng cục bộ để chọn chất lượng hiển thị, không gửi ra ngoài và không định danh thiết bị.</p><h3>Nguồn</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Giấy phép dữ liệu <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Hình học và dữ liệu gốc <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Đọc công bố nguồn <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}

