import {useEffect,useMemo,useState} from 'react';
type Meridian={id:string;code:string;vietnameseName:string;englishName:string;pointIds:string[];path3d:number[][];reviewStatus:string;spatialStatus:string;sources:string[]};
type Acupoint={id:string;code:string;vietnameseName?:string|null;englishName?:string|null;meridianId:string;position3d?:{x:number;y:number;z:number}|null;references?:string[];sources?:string[]};
type Tab='points'|'meridians'|'anatomy'|'assistant';
const norm=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().trim();
export default function YhctStudyPanel(){
 const [open,setOpen]=useState(false),[tab,setTab]=useState<Tab>('meridians'),[meridians,setMeridians]=useState<Meridian[]>([]),[points,setPoints]=useState<Acupoint[]>([]),[query,setQuery]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState('Dữ liệu local đã sẵn sàng sau khi tải.');
 useEffect(()=>{let alive=true;Promise.all([fetch('/data/meridians.json').then(async r=>(await r.json()) as Meridian[]),fetch('/data/acupoints.json').then(async r=>(await r.json()) as Acupoint[])]).then(([m,p])=>{if(alive){setMeridians(m);setPoints(p)}}).catch(()=>{if(alive)setAnswer('Không tải được cơ sở dữ liệu local. Hãy thử tải lại ứng dụng.')});return()=>{alive=false}},[]);
 const filtered=useMemo(()=>{const q=norm(query);if(!q)return tab==='points'?points:meridians;const rows=tab==='points'?points:meridians;return rows.filter((r:any)=>[r.code,r.vietnameseName,r.englishName].filter(Boolean).some((v:string)=>norm(v).includes(q))).slice(0,80)},[query,tab,points,meridians]);
 const ask=()=>{const q=norm(question);if(!q){setAnswer('Nhập câu hỏi dựa trên dữ liệu đã kiểm duyệt trong ứng dụng.');return}
  const exactPoint=points.find(p=>q.includes(norm(p.code))||Boolean(p.vietnameseName&&q.includes(norm(p.vietnameseName))));
  if(exactPoint){const m=meridians.find(x=>x.id===exactPoint.meridianId);setAnswer(`${exactPoint.code}${exactPoint.vietnameseName?' · '+exactPoint.vietnameseName:''} thuộc ${m?.vietnameseName||exactPoint.meridianId}. Nguồn: ${(exactPoint.sources||exactPoint.references||[]).join(', ')||'record đã kiểm duyệt'}.`);return}
  const exactMeridian=meridians.find(m=>q.includes(norm(m.code))||q.includes(norm(m.vietnameseName))||q.includes(norm(m.englishName)));
  if(exactMeridian){if(q.includes('huyet')){const owned=points.filter(p=>p.meridianId===exactMeridian.id);setAnswer(owned.length?`${exactMeridian.vietnameseName} hiện có ${owned.length} huyệt đã kiểm duyệt trong app: ${owned.map(p=>p.code).join(', ')}.`:`${exactMeridian.vietnameseName} có record nomenclature đã kiểm tra, nhưng chưa có danh sách huyệt được phép xuất bản trong runtime hiện tại.`)}else setAnswer(`${exactMeridian.code} · ${exactMeridian.vietnameseName} (${exactMeridian.englishName}). Trạng thái không gian: ${exactMeridian.spatialStatus}; chưa hiển thị đường 3D nếu chưa được đăng ký.`);return}
  if(/st\s*36|lu\s*9|lu\s*5|hop coc|giai khe/.test(q)){setAnswer('Không tìm thấy trong cơ sở dữ liệu đã kiểm duyệt. Hệ thống không tự suy đoán vị trí hoặc công năng huyệt.');return}
  setAnswer('Không tìm thấy trong cơ sở dữ liệu đã kiểm duyệt.');
 };
 return <><button className="yhct-launch glass" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls="yhct-study-panel">YHCT <span>{meridians.length} kinh · {points.length} huyệt</span></button>
 {open&&<aside id="yhct-study-panel" className="yhct-panel glass" aria-label="Huyệt vị, kinh lạc và trợ lý học tập">
  <div className="yhct-head"><div><strong>Huyệt vị · Kinh lạc</strong><small>HIU CLB YHCT · zero-token default</small></div><button onClick={()=>setOpen(false)} aria-label="Đóng bảng YHCT">×</button></div>
  <div className="yhct-tabs">{([['meridians','Kinh'],['points','Huyệt'],['anatomy','Giải phẫu'],['assistant','Trợ lý']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {(tab==='meridians'||tab==='points')&&<><input className="yhct-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==='points'?'Tìm mã/tên huyệt…':'Tìm mã/tên kinh…'} aria-label="Tìm dữ liệu YHCT"/><div className="yhct-list">{filtered.length?filtered.map((r:any)=><article key={r.id}><b>{r.code}</b><span>{r.vietnameseName||r.englishName}</span><small>{tab==='meridians'?(r.path3d?.length?'Đã có đường 3D':'Chưa đăng ký đường 3D'):(r.position3d?'Đã có anchor 3D':'Chưa có anchor 3D')}</small></article>):<p>Không có record đã kiểm duyệt phù hợp.</p>}</div></>}
  {tab==='anatomy'&&<div className="yhct-copy"><strong>Giải phẫu quanh huyệt</strong><p>Viewer BodyParts3D có 15 nhóm hiển thị gồm xương, cơ, động mạch, tĩnh mạch, thần kinh, cơ quan và bề mặt cơ thể. Quan hệ quanh huyệt chỉ được bật khi huyệt có anchor và quan hệ đã xác minh.</p><p className="guard">Không suy luận cấu trúc nguy hiểm chỉ từ khoảng cách mesh.</p></div>}
  {tab==='assistant'&&<div className="yhct-assistant"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ví dụ: Kinh Phế có dữ liệu gì?"/><button onClick={ask}>Tra cứu local</button><p>{answer}</p><small>Không dùng API key · không gọi cloud LLM · không bịa khi thiếu dữ liệu.</small></div>}
  <div className="yhct-modes"><button>Khám phá</button><button disabled={!points.length}>Học theo kinh</button><button disabled={!points.length}>Quiz 3D</button><button disabled={!points.length}>Simulation Lab</button></div>
  <footer>Chỉ dùng cho giáo dục/mô phỏng. Không thay thế đào tạo thực hành có giám sát.</footer>
 </aside>}</>;
}
