import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export const REVIEW_STATUSES=new Set(['UNVERIFIED','SOURCE_VERIFIED','FACULTY_REVIEWED','PUBLISHED']);
export const SOURCE_USE=new Set(['DIRECT_USE','REFERENCE_ONLY','QUARANTINE']);
export function readJson(file){return JSON.parse(fs.readFileSync(file,'utf8'))}
export function sha256Text(text){return crypto.createHash('sha256').update(text).digest('hex')}
export function isFinite3(v){return Array.isArray(v)&&v.length===3&&v.every(Number.isFinite)}
export function validateContent({root=process.cwd()}={}){
 const errors=[],warnings=[];const sf=path.join(root,'content/sources/sources.json'),mf=path.join(root,'content/meridians/meridians.json'),pf=path.join(root,'content/acupoints/acupoints.json');
 const sources=readJson(sf),meridians=readJson(mf),points=readJson(pf);const sm=new Map(),mm=new Map();
 for(const s of sources){if(!s.id||sm.has(s.id))errors.push('Duplicate/missing source id: '+String(s.id));if(!SOURCE_USE.has(s.status))errors.push('Invalid source status: '+s.id);if(s.status==='DIRECT_USE'&&(!s.assetDataLicense||/UNKNOWN|UNVERIFIED|NEEDS/i.test(s.assetDataLicense)))errors.push('DIRECT_USE source has unresolved license: '+s.id);sm.set(s.id,s)}
 for(const m of meridians){if(!m.id||!m.code||mm.has(m.id))errors.push('Duplicate/missing meridian: '+String(m.id));if(!REVIEW_STATUSES.has(m.reviewStatus))errors.push('Invalid meridian reviewStatus: '+m.id);if(!Array.isArray(m.sources)||!m.sources.length)errors.push('Meridian missing source: '+m.id);for(const sid of m.sources||[])if(!sm.has(sid))errors.push('Meridian '+m.id+' references unknown source '+sid);if(!Array.isArray(m.path3d))errors.push('Meridian path3d must be array: '+m.id);for(const p of m.path3d||[])if(!isFinite3(p))errors.push('Invalid 3D path coordinate: '+m.id);mm.set(m.id,m)}
 const codes=new Set();for(const p of points){if(!p.id||!p.code)errors.push('Point missing id/code');if(codes.has(p.code))errors.push('Duplicate acupoint code: '+p.code);codes.add(p.code);if(!mm.has(p.meridianId))errors.push('Point '+p.code+' references unknown meridian '+p.meridianId);const status=p.reviewStatus||p.verificationStatus;if(!REVIEW_STATUSES.has(status))errors.push('Invalid point review status: '+p.code);for(const sid of p.sources||[])if(!sm.has(sid))errors.push('Point '+p.code+' references unknown source '+sid);if(p.position3d!=null){if(!isFinite3([p.position3d.x,p.position3d.y,p.position3d.z]))errors.push('Invalid point xyz: '+p.code);for(const k of ['coordinateSystem','surfaceStructureId','source'])if(!p.position3d[k])errors.push('Point '+p.code+' position missing '+k);if(status==='UNVERIFIED')errors.push('Unverified point may not publish a 3D position: '+p.code)}const clinical=['functions','traditionalIndications','caution','needleAngle','needleDepth','method'].some(k=>p[k]!=null&&(Array.isArray(p[k])?p[k].length>0:true));if(clinical&&p.reviewStatus!=='PUBLISHED')errors.push('Clinical/simulation claim requires PUBLISHED: '+p.code)}
 return {errors,warnings,counts:{sources:sources.length,meridians:meridians.length,acupoints:points.length},files:{sourceFile:sf,meridianFile:mf,pointFile:pf}};
}
export function lookupByCode(records,code){const q=String(code||'').trim().toUpperCase();return records.find(x=>String(x.code||'').toUpperCase()===q)||null}
export function normalizeVi(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().trim()}
export function searchRecords(records,q){q=normalizeVi(q);if(!q)return[];return records.filter(r=>[r.code,r.vietnameseName,r.englishName,r.pinyin,r.chineseName].filter(Boolean).some(v=>normalizeVi(v).includes(q)))}
